from selenium.webdriver.common.by import By
SEARCHBYID = (By.CSS_SELECTOR,'input#rbAgentsSearchCriteria[value="2"]')
INSERT_AGENT_ID = (By.CSS_SELECTOR,'input#tbAgentId')
SEARCH_BUTTON = (By.CSS_SELECTOR,'#btSearch')
SELECT_AGENT = (By.XPATH,'//td[@class="first_name clickable_cell"]')
MODIFY_AGENT = (By.XPATH,'//div[@class="content_section section_buttons"]//a[1]')
ALLOCATED_TERMINALS = (By.CSS_SELECTOR,'lAllocatedTerminals')
TERMINAL_FOR_TEST = (By.XPATH,'//option[@value="20226"]')
ALOCATE_TERMINAL_BTN = (By.CSS_SELECTOR,'#btnAlocateTerminal')
DEALOCATE_TERMINAL_BTN = (By.CSS_SELECTOR, '#btnDealocateTerminal')
PHONE_TEXTBOX= (By.CSS_SELECTOR,'#MobilePhone')
ADDPHONE_BUTTON = (By.CSS_SELECTOR,'#btnAddMobilePhone')
EXTERNAL_REFERENCE = (By.CSS_SELECTOR,'#External_Reference')
EXTERNAL_REFERENCE_ERR = (By.CSS_SELECTOR,'#External_Reference-error')
